name: papermillR
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - ansiwrap=0.8.4
  - appdirs=1.4.3
  - attrs=19.3.0
  - backcall=0.1.0
  - binutils_impl_linux-64=2.34
  - binutils_linux-64=2.34
  - black=19.10b0
  - bleach=3.1.3
  - bwidget=1.9.14
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - cairo=1.16.0
  - certifi=2019.11.28
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.1
  - colorama=0.4.3
  - cryptography=2.8
  - curl=7.68.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - fontconfig=2.13.1
  - freetype=2.10.1
  - fribidi=1.0.9
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=7.3.0
  - gfortran_linux-64=7.3.0
  - gitdb=4.0.2
  - gitpython=3.1.0
  - glib=2.58.3
  - graphite2=1.3.13
  - gsl=2.6
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - harfbuzz=2.4.0
  - icu=64.2
  - idna=2.9
  - importlib-metadata=1.5.0
  - importlib_metadata=1.5.0
  - ipykernel=5.2.0
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - jedi=0.16.0
  - jinja2=2.11.1
  - jpeg=9c
  - jsonschema=3.2.0
  - jupyter_client=6.1.0
  - jupyter_core=4.6.3
  - jupytext=1.4.1
  - krb5=1.16.4
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.68.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.3.0
  - libgomp=9.2.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libsodium=1.0.17
  - libssh2=1.8.2
  - libstdcxx-ng=9.2.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.8.3
  - make=4.3
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mypy_extensions=0.4.3
  - nbclient=0.1.0
  - nbconvert=5.6.1
  - nbdime=2.0.0
  - nbformat=5.0.4
  - ncurses=6.1
  - notebook=6.0.3
  - openssl=1.1.1e
  - pandoc=2.9.2
  - pandocfilters=1.4.2
  - pango=1.42.4
  - papermill=2.0.0
  - parso=0.6.2
  - pathspec=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - pixman=0.38.0
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.4
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.8.2
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pyyaml=5.3.1
  - pyzmq=19.0.0
  - r-assertthat=0.2.1
  - r-backports=1.1.5
  - r-base=3.6.2
  - r-base64enc=0.1_3
  - r-cli=2.0.2
  - r-crayon=1.3.4
  - r-digest=0.6.25
  - r-ellipsis=0.3.0
  - r-evaluate=0.14
  - r-fansi=0.4.1
  - r-glue=1.3.2
  - r-htmltools=0.4.0
  - r-irdisplay=0.7
  - r-irkernel=1.1
  - r-jsonlite=1.6.1
  - r-pbdzmq=0.3_3
  - r-pillar=1.4.3
  - r-rcpp=1.0.4
  - r-repr=1.1.0
  - r-rlang=0.4.5
  - r-utf8=1.1.4
  - r-uuid=0.1_4
  - r-vctrs=0.2.4
  - r-zeallot=0.1.0
  - readline=8.0
  - regex=2020.2.20
  - requests=2.23.0
  - sed=4.7
  - send2trash=1.5.0
  - setuptools=46.1.1
  - six=1.14.0
  - smmap=3.0.1
  - sqlite=3.30.1
  - tenacity=6.1.0
  - terminado=0.8.3
  - testpath=0.4.4
  - textwrap3=0.9.2
  - tk=8.6.10
  - tktable=2.10
  - toml=0.10.0
  - tornado=6.0.4
  - tqdm=4.43.0
  - traitlets=4.3.3
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.1
  - urllib3=1.25.7
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - wheel=0.34.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.2.2
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4

